### ISSUE TITLE
Prevent minified CSS from creating sourcemap?

### ISSUE THREAD

**Issue by jaminroe** [murphydanger/gulp-minify-css#134] opened 2015-12-19 12:41 UTC
How do I prevent this plug-in from compiling a minified version of the source map? Example:

![image](https://cloud.githubusercontent.com/assets/1559447/11911259/a7e6c05a-a5dd-11e5-9c82-1839f8d01cd2.png)

This is what I have in my gulpfile for this task:
```
// Compile Our Sass
gulp.task('sass', function() {
    return gulp.src('*.scss')
        .pipe(sourcemaps.init())
        .pipe(sass(sassOptions).on('error', sass.logError))
        .pipe(autoprefixer())
        .pipe(gulpIf('*.css', minifyCss()))
        .pipe(rename({
            suffix: '.min'
        }))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('./'));
});
```

If I just do: `.pipe(minifyCss())` it doesn't create a .min version of oneweb.css, it just creates compressed/minified css in that file. :(

**Comment by shinnn** [comment] 2015-12-19 12:49
I cannot run your gulpfile.

```
gulp.task('sass', function() {
^

ReferenceError: gulp is not defined
```

**Comment by shinnn** [comment] 2015-12-19 12:52
Just a duplicate of https://github.com/jakubpawlowicz/clean-css/issues/716#issuecomment-165962992, and the clean-css author already answered well.

**Closed by shinnn** 2015-12-19 12:52 UTC
Labels: invalid

**Comment by jaminroe** [comment] 2015-12-19 16:27
I just was showing a simplified version of my file. Thanks, wasn't sure if you would give me a different solution.
